services:
  - type: web
    name: missing-persons-ar-backend
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      PIP_ONLY_BINARY=:all: pip install --no-cache-dir -r requirements.txt
      python manage.py migrate
      python manage.py shell < create_superuser.py
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi --log-file -
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: missing-persons-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings_prod"
      - key: ALLOWED_HOSTS
        value: "missing-persons-ar-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend.vercel.app"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin123"
databases:
  - name: missing-persons-db
    plan: free
